### ISSUE TITLE
discord channel gone? invalid invite? 

### ISSUE THREAD

**Issue by kocoman2** [hack-different/apple-knowledge#109]

**Comment by ghost** [comment]
For some reason the discord vanity link was removed but @rickmark fixed it again :)

**Comment by omrikurtz** [comment]
Updating that https://discord.gg/hackdifferent still doesn’t work. @0x8ff is this the link you’re referring to?

**Comment by ghost** [comment]
Not sure why it's not working, the server is level 3, maybe it has to be set again every time it loses a level?

Anyway, this invite works: https://discord.gg/NAxRYvysuc
